<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { Plus, Check, Trash2, ShoppingCart, ChefHat, X, Minus, Copy } from 'lucide-vue-next';
import DataManager from '../utils/storage';
import type { ShoppingItem, Recipe } from '../utils/storage';

const shoppingList = ref<ShoppingItem[]>([]);
const showRecipeSelector = ref(false);
const showManualAdd = ref(false);

// Recipe Selector State
const allRecipes = ref<Recipe[]>([]);
const selectedRecipesMap = ref<Map<string, number>>(new Map()); // id -> quantity

// Manual Add State
const manualItem = ref({ name: '', quantity: 1, unit: '个' });

onMounted(() => {
  loadList();
  allRecipes.value = DataManager.getRecipes();
});

const loadList = () => {
  shoppingList.value = DataManager.getShoppingList();
};

const toggleBought = (item: ShoppingItem) => {
  item.isBought = !item.isBought;
  saveList();
};

const deleteItem = (index: number) => {
  shoppingList.value.splice(index, 1);
  saveList();
};

const saveList = () => {
  DataManager.saveShoppingList(shoppingList.value);
};

const openRecipeSelector = () => {
  selectedRecipesMap.value.clear();
  showRecipeSelector.value = true;
};

const incrementRecipe = (id: string) => {
  const current = selectedRecipesMap.value.get(id) || 0;
  selectedRecipesMap.value.set(id, current + 1);
};

const decrementRecipe = (id: string) => {
  const current = selectedRecipesMap.value.get(id) || 0;
  if (current > 0) {
    if (current === 1) {
      selectedRecipesMap.value.delete(id);
    } else {
      selectedRecipesMap.value.set(id, current - 1);
    }
  }
};

const generateFromRecipes = () => {
  const newItems: ShoppingItem[] = [];

  selectedRecipesMap.value.forEach((count, recipeId) => {
    const recipe = allRecipes.value.find(r => r.id === recipeId);
    if (recipe) {
      recipe.ingredients.forEach(ing => {
        newItems.push({
          id: '', // Generated by DataManager
          name: ing.name,
          quantity: ing.quantity * count,
          unit: ing.unit,
          isBought: false,
          isManual: false,
          estimatedPrice: 0 // Could calculate from Price DB
        });
      });
    }
  });

  DataManager.addToShoppingList(newItems);
  loadList();
  showRecipeSelector.value = false;
};

const clearList = () => {
  if (confirm('确定要清空所有清单吗？')) {
    shoppingList.value = [];
    saveList();
  }
};

const addManualItem = () => {
  if (!manualItem.value.name) return;
  DataManager.addToShoppingList([{
    id: '',
    name: manualItem.value.name,
    quantity: manualItem.value.quantity,
    unit: manualItem.value.unit,
    isBought: false,
    isManual: true,
    estimatedPrice: 0
  }]);
  loadList();
  manualItem.value = { name: '', quantity: 1, unit: '个' };
  showManualAdd.value = false;
};

const totalEstimatedCost = computed(() => {
  return shoppingList.value.reduce((total, item) => {
    if (item.isBought) return total; // Optional: Exclude bought? Or keep all. Let's keep all.
    const priceInfo = DataManager.getPrice(item.name);
    if (priceInfo && priceInfo.unit === item.unit) {
      return total + (priceInfo.price * item.quantity);
    }
    return total;
  }, 0);
});

const copyList = async () => {
  if (shoppingList.value.length === 0) return;
  
  const lines = ['【待买清单】'];
  shoppingList.value.forEach(item => {
    const check = item.isBought ? '☑' : '☐';
    lines.push(`${check} ${item.name} ${item.quantity}${item.unit}`);
  });
  lines.push('----------------');
  lines.push(`预估总价：¥${totalEstimatedCost.value.toFixed(1)}`);
  
  const text = lines.join('\n');
  try {
    await navigator.clipboard.writeText(text);
    alert('清单已复制到剪贴板！');
  } catch (err) {
    alert('复制失败，请截图保存');
  }
};
</script>

<template>
  <div class="p-4 space-y-6 pb-24 min-h-screen relative">
    <header class="flex justify-between items-center mt-2">
      <div>
        <h1 class="text-2xl font-bold text-neu-text tracking-wide flex items-center">
          采购清单 <ShoppingCart :size="24" class="ml-2 text-neu-primary" />
          <span v-if="shoppingList.length" class="ml-2 bg-neu-primary text-white text-xs px-2 py-0.5 rounded-full font-bold shadow-md">
            {{ shoppingList.length }}
          </span>
        </h1>
        <p class="text-xs text-neu-text-secondary mt-1 flex items-center font-medium">
          预计花费: <span class="font-bold text-neu-primary ml-1 text-sm">¥{{ totalEstimatedCost.toFixed(1) }}</span>
        </p>
      </div>
      <div class="flex space-x-3">
        <button 
          v-if="shoppingList.length > 0"
          @click="copyList" 
          class="neu-btn-icon text-blue-500 hover:text-blue-600"
          title="复制清单"
        >
          <Copy :size="20" />
        </button>
        <button 
          v-if="shoppingList.length > 0"
          @click="clearList" 
          class="neu-btn-icon text-red-400 hover:text-red-500"
          title="清空清单"
        >
          <Trash2 :size="20" />
        </button>
        <button @click="showManualAdd = true" class="neu-btn-icon text-neu-text-secondary">
          <Plus :size="20" />
        </button>
        <button @click="openRecipeSelector" class="neu-btn-icon text-neu-primary">
          <ChefHat :size="20" />
        </button>
      </div>
    </header>

    <!-- List -->
    <div class="space-y-4">
      <div v-if="shoppingList.length === 0" class="text-center py-20 text-neu-text-secondary opacity-60">
        <ShoppingCart :size="48" class="mx-auto mb-4" />
        <p>清单是空的</p>
        <p class="text-xs mt-1">点击右上角图标添加</p>
      </div>

      <div
        v-for="(item, index) in shoppingList"
        :key="index"
        class="neu-flat p-4 rounded-2xl flex items-center group transition-all duration-300"
        :class="{ 'opacity-60 grayscale': item.isBought }"
      >
        <button
          @click="toggleBought(item)"
          class="w-6 h-6 rounded-md mr-4 transition-all duration-300 flex items-center justify-center border border-neu-secondary/20"
          :class="item.isBought ? 'neu-pressed text-green-500' : 'neu-flat text-transparent hover:text-green-200'"
        >
          <Check :size="16" stroke-width="4" v-if="item.isBought" />
        </button>
        
        <div class="flex-1 transition-all duration-300" :class="{ 'line-through text-neu-text-secondary': item.isBought, 'text-neu-text': !item.isBought }">
          <h3 class="font-bold">{{ item.name }}</h3>
          <p class="text-xs text-neu-text-secondary font-medium">{{ item.quantity }} {{ item.unit }}</p>
        </div>

        <button @click="deleteItem(index)" class="neu-btn-icon w-10 h-10 text-neu-text-secondary hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity">
          <Trash2 :size="18" />
        </button>
      </div>
    </div>

    <!-- Recipe Selector Modal -->
    <div v-if="showRecipeSelector" class="fixed inset-0 z-50 flex items-end sm:items-center justify-center">
      <div class="absolute inset-0 bg-neu-base/80 backdrop-blur-sm" @click="showRecipeSelector = false"></div>
      
      <div class="bg-neu-base w-full max-w-sm rounded-t-3xl sm:rounded-3xl max-h-[80vh] flex flex-col neu-float relative animate-in slide-in-from-bottom duration-300">
        <div class="p-6 border-b border-neu-secondary/20 flex justify-between items-center">
          <h3 class="font-bold text-lg text-neu-text">从菜单添加</h3>
          <button @click="showRecipeSelector = false" class="neu-btn-icon w-10 h-10">
            <X :size="24" />
          </button>
        </div>
        
        <div class="flex-1 overflow-y-auto p-6 space-y-4 scrollbar-hide">
          <div
            v-for="recipe in allRecipes"
            :key="recipe.id"
            class="p-4 rounded-2xl flex justify-between items-center transition-colors neu-flat"
          >
            <span class="font-bold text-neu-text flex-1">{{ recipe.name }}</span>
            
            <div class="flex items-center space-x-4">
              <button 
                @click.stop="decrementRecipe(recipe.id)"
                class="neu-btn-icon w-8 h-8 text-neu-text-secondary"
                :class="{ 'opacity-30 cursor-not-allowed': !selectedRecipesMap.get(recipe.id) }"
                :disabled="!selectedRecipesMap.get(recipe.id)"
              >
                <Minus :size="14" />
              </button>
              
              <span class="w-6 text-center font-bold text-neu-text">
                {{ selectedRecipesMap.get(recipe.id) || 0 }}
              </span>

              <button 
                @click.stop="incrementRecipe(recipe.id)"
                class="neu-btn-icon w-8 h-8 text-neu-primary"
              >
                <Plus :size="14" />
              </button>
            </div>
          </div>
        </div>

        <div class="p-6 border-t border-neu-secondary/20">
          <button
            @click="generateFromRecipes"
            class="neu-btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
            :disabled="selectedRecipesMap.size === 0"
          >
            生成清单 ({{ Array.from(selectedRecipesMap.values()).reduce((a, b) => a + b, 0) }} 道菜)
          </button>
        </div>
      </div>
    </div>

    <!-- Manual Add Modal -->
    <div v-if="showManualAdd" class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div class="absolute inset-0 bg-neu-base/80 backdrop-blur-sm" @click="showManualAdd = false"></div>
      
      <div class="bg-neu-base w-full max-w-xs rounded-3xl p-8 neu-float relative animate-in zoom-in duration-200">
        <h3 class="font-bold text-lg mb-6 text-neu-text">添加临时物品</h3>
        <div class="space-y-4 mb-8">
          <div>
            <label class="block text-xs font-bold text-neu-text-secondary mb-2 uppercase tracking-wider">物品名称</label>
            <input v-model="manualItem.name" placeholder="如: 垃圾袋" class="neu-input" autoFocus />
          </div>
          <div class="flex space-x-3">
            <div class="w-20">
              <label class="block text-xs font-bold text-neu-text-secondary mb-2 uppercase tracking-wider text-center">数量</label>
              <input v-model.number="manualItem.quantity" type="number" class="neu-input text-center" placeholder="1" />
            </div>
            <div class="flex-1">
              <label class="block text-xs font-bold text-neu-text-secondary mb-2 uppercase tracking-wider text-center">单位</label>
              <input v-model="manualItem.unit" placeholder="个" class="neu-input text-center" />
            </div>
          </div>
        </div>
        <div class="flex space-x-4">
          <button @click="showManualAdd = false" class="flex-1 py-3 text-neu-text-secondary font-bold hover:text-neu-text transition-colors">取消</button>
          <button @click="addManualItem" class="flex-1 neu-btn-primary py-3 text-sm">添加</button>
        </div>
      </div>
    </div>
  </div>
</template>
